FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm

RUN apt-get update 
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y firefox-esr

RUN export DEBIAN_FRONTEND=noninteractive \
    && curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_$(dpkg --print-architecture).deb -o /tmp/chrome.deb \
    && apt-get -y install /tmp/chrome.deb

